[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "packagename"
version = "0.1.0"
dependencies = ["numpy"]

[project.optional-dependencies]
dev = ["ruff", "pytest"]

[tool.ruff]
select = [
    "E",
    "F", # pyflakes
    "B",
    "I", # imports
    "N", # names
]
# ruff will use the .gitignore to exclude files and directories
# exclude = ["venv"]
line-length = 80
indent-width = 2

[tool.pyright]
venvPath = "."
venv = "venv"
typeCheckingMode = "strict"
reportMissingTypeStubs = false
